# Generated by Django 5.2.7 on 2025-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField()),
                ("workplace", models.CharField()),
                ("photo", models.ImageField(upload_to="member_photo/")),
                ("bio", models.TextField()),
            ],
        ),
    ]
