# Generated by Django 5.2.7 on 2025-10-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="bio_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="bio_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="bio_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="full_name_en",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="full_name_ru",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="full_name_uz",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="workplace_en",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="workplace_ru",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="workplace_uz",
            field=models.CharField(null=True),
        ),
    ]
